version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    env_file: .env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

  backend:
    build: .
    env_file: .env
    volumes:
      - static:/app/static
    depends_on:
      - db
      - redis
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --noinput
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      - backend

  gateway:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - static:/app/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - backend

volumes:
  postgres_data:
  static:

networks:
  backend:
